### ISSUE TITLE
A measurement holds the exclusive lock while it waits for validation slots

### ISSUE THREAD

**Issue by michaelJwilson** [michaelJwilson/snakes_and_ladders#427]
### Desired outcome

`with_lock measure` holds nothing while it waits. A long validation delays a measurement, as it must, but does not stall every other measurement behind it, and an agent cannot stall itself.

### Why it matters

`with_lock measure` takes `measure.lock` **first**, then blocks acquiring all three validate slots. While blocked it is holding the exclusive lock, so:

- no other measurement on the host can start, however long the wait;
- two validate slots sit free while the machine does nothing with them;
- an agent that runs a measurement while its own validation is still running **stalls against itself**.

Observed at 00:55 on 2026-09-09, all three at once:

```
measure.lock    HELD   pid 11305 (flock), child 2568 blocked in --hold-all-validate-slots
validate.1      HELD   pid 22868, a 40-minute pytest
validate.2      free
validate.3      free
```

Every process was `cwd=/home/user/wt-397` — one agent, holding the exclusive lock in one hand and the slot it needs in the other. It clears only when the pytest ends, and `SAL_LOCK_WAIT` (1800 s) would otherwise fail the measurement after half an hour of holding a lock it never got to use.

This is a lock-ordering defect introduced by #418 part 1 (PR #419), not a misuse: the caller did nothing wrong.

### Submodule

infra

### Scope and non-goals

In scope: the acquisition order and shape of the two locks, and the tests that pin the trade.

Not in scope: what counts as a measurement versus a validation, and the three-slot cap — both measured and both correct. The `--wide` option is #425's business, not this ticket's.

### The likely fix, which is also a simplification

Make it one readers–writer lock rather than four locks:

- **validate** takes a *shared* `flock -s` on `host.lock`, plus one of the three slot files to cap concurrency;
- **measure** takes an *exclusive* `flock -x` on `host.lock` and nothing else.

A measurement then waits on a single lock and holds nothing until it holds everything, so the inversion cannot arise. It also deletes `_hold_all_validate_slots`, the recursion through `bash "${BASH_SOURCE[0]}"`, and the fallback that re-entry needed — about a third of `infra/locks.sh`, and the part that has produced the most defects.

Note for whoever takes this: `flock` does not promise writer preference, so a stream of validations could in principle starve a measurement. Measure whether that happens at the current agent cap before adding machinery to prevent it.

### How it will be validated

A test that reproduces the inversion and fails on the current implementation: start a long validation, then start a measurement, and assert that a *second* measurement is not blocked by the first one's wait — and that the first holds no lock until it can run. Plus the existing ten tests in `tests/regression/test_host_locks.py`, unchanged, since the guarantees they pin must survive.

**Comment by michaelJwilson** [comment]
Branch: `claude/infra-427-rwlock`, from `main`.

---
_Generated by [Claude Code](https://claude.ai/code)_
